/**
 * FIFA World Cup 2026 — hardcoded group-stage match schedule (UTC).
 * Source: ESPN API (site.api.espn.com) + official FIFA schedule PDF.
 *
 * Keys are match IDs (m1–m72) matching the pairs generated by matches.js.
 * Times are stored in UTC so the frontend can convert to any local timezone.
 * No API sync required — these dates are fixed and will never change.
 */
export const MATCH_DATES = {

  // ── Group A: Mexico · South Africa · Korea Republic · Czechia ───────────
  m1:  '2026-06-11T19:00:00Z',  // Mexico        vs South Africa
  m2:  '2026-06-12T02:00:00Z',  // Korea Rep.    vs Czechia
  m3:  '2026-06-19T01:00:00Z',  // Mexico        vs Korea Republic
  m4:  '2026-06-18T16:00:00Z',  // South Africa  vs Czechia
  m5:  '2026-06-25T01:00:00Z',  // Mexico        vs Czechia
  m6:  '2026-06-25T01:00:00Z',  // South Africa  vs Korea Republic

  // ── Group B: Canada · Bosnia and Herzegovina · Qatar · Switzerland ───────
  m7:  '2026-06-12T19:00:00Z',  // Canada        vs Bosnia and Herzegovina
  m8:  '2026-06-13T19:00:00Z',  // Qatar         vs Switzerland
  m9:  '2026-06-18T22:00:00Z',  // Canada        vs Qatar
  m10: '2026-06-18T19:00:00Z',  // Bosnia        vs Switzerland
  m11: '2026-06-24T19:00:00Z',  // Canada        vs Switzerland
  m12: '2026-06-24T19:00:00Z',  // Bosnia        vs Qatar

  // ── Group C: Brazil · Morocco · Haiti · Scotland ─────────────────────────
  m13: '2026-06-13T22:00:00Z',  // Brazil        vs Morocco
  m14: '2026-06-14T01:00:00Z',  // Haiti         vs Scotland
  m15: '2026-06-20T00:30:00Z',  // Brazil        vs Haiti
  m16: '2026-06-19T22:00:00Z',  // Morocco       vs Scotland
  m17: '2026-06-24T22:00:00Z',  // Brazil        vs Scotland
  m18: '2026-06-24T22:00:00Z',  // Morocco       vs Haiti

  // ── Group D: United States · Paraguay · Australia · Türkiye ─────────────
  m19: '2026-06-13T01:00:00Z',  // United States vs Paraguay
  m20: '2026-06-14T04:00:00Z',  // Australia     vs Türkiye
  m21: '2026-06-19T19:00:00Z',  // United States vs Australia
  m22: '2026-06-20T03:00:00Z',  // Paraguay      vs Türkiye
  m23: '2026-06-26T02:00:00Z',  // United States vs Türkiye
  m24: '2026-06-26T02:00:00Z',  // Paraguay      vs Australia

  // ── Group E: Germany · Curaçao · Ivory Coast · Ecuador ──────────────────
  m25: '2026-06-14T17:00:00Z',  // Germany       vs Curaçao
  m26: '2026-06-14T23:00:00Z',  // Ivory Coast   vs Ecuador
  m27: '2026-06-20T20:00:00Z',  // Germany       vs Ivory Coast
  m28: '2026-06-21T00:00:00Z',  // Curaçao       vs Ecuador
  m29: '2026-06-25T20:00:00Z',  // Germany       vs Ecuador
  m30: '2026-06-25T20:00:00Z',  // Curaçao       vs Ivory Coast

  // ── Group F: Netherlands · Japan · Sweden · Tunisia ──────────────────────
  m31: '2026-06-14T20:00:00Z',  // Netherlands   vs Japan
  m32: '2026-06-15T02:00:00Z',  // Sweden        vs Tunisia
  m33: '2026-06-20T17:00:00Z',  // Netherlands   vs Sweden
  m34: '2026-06-21T04:00:00Z',  // Japan         vs Tunisia
  m35: '2026-06-25T23:00:00Z',  // Netherlands   vs Tunisia
  m36: '2026-06-25T23:00:00Z',  // Japan         vs Sweden

  // ── Group G: Belgium · Egypt · Iran · New Zealand ────────────────────────
  m37: '2026-06-15T19:00:00Z',  // Belgium       vs Egypt
  m38: '2026-06-16T01:00:00Z',  // Iran          vs New Zealand
  m39: '2026-06-21T19:00:00Z',  // Belgium       vs Iran
  m40: '2026-06-22T01:00:00Z',  // Egypt         vs New Zealand
  m41: '2026-06-27T03:00:00Z',  // Belgium       vs New Zealand
  m42: '2026-06-27T03:00:00Z',  // Egypt         vs Iran

  // ── Group H: Spain · Cape Verde · Saudi Arabia · Uruguay ─────────────────
  m43: '2026-06-15T16:00:00Z',  // Spain         vs Cape Verde
  m44: '2026-06-15T22:00:00Z',  // Saudi Arabia  vs Uruguay
  m45: '2026-06-21T16:00:00Z',  // Spain         vs Saudi Arabia
  m46: '2026-06-21T22:00:00Z',  // Cape Verde    vs Uruguay
  m47: '2026-06-27T00:00:00Z',  // Spain         vs Uruguay
  m48: '2026-06-27T00:00:00Z',  // Cape Verde    vs Saudi Arabia

  // ── Group I: France · Senegal · Iraq · Norway ────────────────────────────
  m49: '2026-06-16T19:00:00Z',  // France        vs Senegal
  m50: '2026-06-16T22:00:00Z',  // Iraq          vs Norway
  m51: '2026-06-22T21:00:00Z',  // France        vs Iraq
  m52: '2026-06-23T00:00:00Z',  // Senegal       vs Norway
  m53: '2026-06-26T19:00:00Z',  // France        vs Norway
  m54: '2026-06-26T19:00:00Z',  // Senegal       vs Iraq

  // ── Group J: Argentina · Algeria · Austria · Jordan ──────────────────────
  m55: '2026-06-17T01:00:00Z',  // Argentina     vs Algeria
  m56: '2026-06-17T04:00:00Z',  // Austria       vs Jordan
  m57: '2026-06-22T17:00:00Z',  // Argentina     vs Austria
  m58: '2026-06-23T03:00:00Z',  // Algeria       vs Jordan
  m59: '2026-06-28T02:00:00Z',  // Argentina     vs Jordan
  m60: '2026-06-28T02:00:00Z',  // Algeria       vs Austria

  // ── Group K: Portugal · DR Congo · Uzbekistan · Colombia ─────────────────
  m61: '2026-06-17T17:00:00Z',  // Portugal      vs DR Congo
  m62: '2026-06-18T02:00:00Z',  // Uzbekistan    vs Colombia
  m63: '2026-06-23T17:00:00Z',  // Portugal      vs Uzbekistan
  m64: '2026-06-24T02:00:00Z',  // DR Congo      vs Colombia
  m65: '2026-06-27T23:30:00Z',  // Portugal      vs Colombia
  m66: '2026-06-27T23:30:00Z',  // DR Congo      vs Uzbekistan

  // ── Group L: England · Croatia · Ghana · Panama ───────────────────────────
  m67: '2026-06-17T20:00:00Z',  // England       vs Croatia
  m68: '2026-06-17T23:00:00Z',  // Ghana         vs Panama
  m69: '2026-06-23T20:00:00Z',  // England       vs Ghana
  m70: '2026-06-23T23:00:00Z',  // Croatia       vs Panama
  m71: '2026-06-27T21:00:00Z',  // England       vs Panama
  m72: '2026-06-27T21:00:00Z',  // Croatia       vs Ghana
}
