/**
 * FIFA World Cup 2026 — hardcoded match schedule (UTC).
 * Source: ESPN API (site.api.espn.com) + official FIFA schedule PDF.
 *
 * Keys are match IDs (m1–m72) matching the pairs generated by matches.js.
 * Knockout dates (m73+) filled in as confirmed; ESPN fetcher overrides if it
 * has a more precise kickoff time.
 * Times are stored in UTC so the frontend can convert to any local timezone.
 *
 * Home/away designations match the official FIFA/ESPN convention.
 */
export const MATCH_DATES = {

  // ── Knockout finals ───────────────────────────────────────────────────────
  m103: '2026-07-18T21:00:00Z',  // 3rd Place  — Sat Jul 18, 5 PM ET / 3 PM MT


  // ── Group A: Mexico · South Africa · Korea Republic · Czechia ───────────
  m1:  '2026-06-11T19:00:00Z',  // Mexico        vs South Africa      (MD1)
  m2:  '2026-06-12T02:00:00Z',  // Korea Rep.    vs Czechia            (MD1)
  m3:  '2026-06-19T01:00:00Z',  // Mexico        vs Korea Republic     (MD2)
  m4:  '2026-06-18T16:00:00Z',  // Czechia       vs South Africa       (MD2)
  m5:  '2026-06-25T01:00:00Z',  // Czechia       vs Mexico             (MD3)
  m6:  '2026-06-25T01:00:00Z',  // South Africa  vs Korea Republic     (MD3)

  // ── Group B: Canada · Bosnia and Herzegovina · Qatar · Switzerland ───────
  m7:  '2026-06-12T19:00:00Z',  // Canada        vs Bosnia and Herz.  (MD1)
  m8:  '2026-06-13T19:00:00Z',  // Qatar         vs Switzerland        (MD1)
  m9:  '2026-06-18T22:00:00Z',  // Canada        vs Qatar              (MD2)
  m10: '2026-06-18T19:00:00Z',  // Switzerland   vs Bosnia and Herz.  (MD2)
  m11: '2026-06-24T19:00:00Z',  // Switzerland   vs Canada             (MD3)
  m12: '2026-06-24T19:00:00Z',  // Bosnia        vs Qatar              (MD3)

  // ── Group C: Brazil · Morocco · Haiti · Scotland ─────────────────────────
  m13: '2026-06-13T22:00:00Z',  // Brazil        vs Morocco            (MD1)
  m14: '2026-06-14T01:00:00Z',  // Haiti         vs Scotland           (MD1)
  m15: '2026-06-20T00:30:00Z',  // Brazil        vs Haiti              (MD2)
  m16: '2026-06-19T22:00:00Z',  // Scotland      vs Morocco            (MD2)
  m17: '2026-06-24T22:00:00Z',  // Scotland      vs Brazil             (MD3)
  m18: '2026-06-24T22:00:00Z',  // Morocco       vs Haiti              (MD3)

  // ── Group D: United States · Paraguay · Australia · Türkiye ─────────────
  m19: '2026-06-13T01:00:00Z',  // United States vs Paraguay           (MD1)
  m20: '2026-06-14T04:00:00Z',  // Australia     vs Türkiye            (MD1)
  m21: '2026-06-19T19:00:00Z',  // United States vs Australia          (MD2)
  m22: '2026-06-20T03:00:00Z',  // Türkiye       vs Paraguay           (MD2)
  m23: '2026-06-26T02:00:00Z',  // Türkiye       vs United States      (MD3)
  m24: '2026-06-26T02:00:00Z',  // Paraguay      vs Australia          (MD3)

  // ── Group E: Germany · Curaçao · Ivory Coast · Ecuador ──────────────────
  m25: '2026-06-14T17:00:00Z',  // Germany       vs Curaçao            (MD1)
  m26: '2026-06-14T23:00:00Z',  // Ivory Coast   vs Ecuador            (MD1)
  m27: '2026-06-20T20:00:00Z',  // Germany       vs Ivory Coast        (MD2)
  m28: '2026-06-21T00:00:00Z',  // Ecuador       vs Curaçao            (MD2)
  m29: '2026-06-25T20:00:00Z',  // Ecuador       vs Germany            (MD3)
  m30: '2026-06-25T20:00:00Z',  // Curaçao       vs Ivory Coast        (MD3)

  // ── Group F: Netherlands · Japan · Sweden · Tunisia ──────────────────────
  m31: '2026-06-14T20:00:00Z',  // Netherlands   vs Japan              (MD1)
  m32: '2026-06-15T02:00:00Z',  // Sweden        vs Tunisia            (MD1)
  m33: '2026-06-20T17:00:00Z',  // Netherlands   vs Sweden             (MD2)
  m34: '2026-06-21T04:00:00Z',  // Tunisia       vs Japan              (MD2)
  m35: '2026-06-25T23:00:00Z',  // Tunisia       vs Netherlands        (MD3)
  m36: '2026-06-25T23:00:00Z',  // Japan         vs Sweden             (MD3)

  // ── Group G: Belgium · Egypt · Iran · New Zealand ────────────────────────
  m37: '2026-06-15T19:00:00Z',  // Belgium       vs Egypt              (MD1)
  m38: '2026-06-16T01:00:00Z',  // Iran          vs New Zealand        (MD1)
  m39: '2026-06-21T19:00:00Z',  // Belgium       vs Iran               (MD2)
  m40: '2026-06-22T01:00:00Z',  // New Zealand   vs Egypt              (MD2)
  m41: '2026-06-27T03:00:00Z',  // New Zealand   vs Belgium            (MD3)
  m42: '2026-06-27T03:00:00Z',  // Egypt         vs Iran               (MD3)

  // ── Group H: Spain · Cape Verde · Saudi Arabia · Uruguay ─────────────────
  m43: '2026-06-15T16:00:00Z',  // Spain         vs Cape Verde         (MD1)
  m44: '2026-06-15T22:00:00Z',  // Saudi Arabia  vs Uruguay            (MD1)
  m45: '2026-06-21T16:00:00Z',  // Spain         vs Saudi Arabia       (MD2)
  m46: '2026-06-21T22:00:00Z',  // Uruguay       vs Cape Verde         (MD2)
  m47: '2026-06-27T00:00:00Z',  // Uruguay       vs Spain              (MD3)
  m48: '2026-06-27T00:00:00Z',  // Cape Verde    vs Saudi Arabia       (MD3)

  // ── Group I: France · Senegal · Iraq · Norway ────────────────────────────
  m49: '2026-06-16T19:00:00Z',  // France        vs Senegal            (MD1)
  m50: '2026-06-16T22:00:00Z',  // Iraq          vs Norway             (MD1)
  m51: '2026-06-22T21:00:00Z',  // France        vs Iraq               (MD2)
  m52: '2026-06-23T00:00:00Z',  // Norway        vs Senegal            (MD2)
  m53: '2026-06-26T19:00:00Z',  // Norway        vs France             (MD3)
  m54: '2026-06-26T19:00:00Z',  // Senegal       vs Iraq               (MD3)

  // ── Group J: Argentina · Algeria · Austria · Jordan ──────────────────────
  m55: '2026-06-17T01:00:00Z',  // Argentina     vs Algeria            (MD1)
  m56: '2026-06-17T04:00:00Z',  // Austria       vs Jordan             (MD1)
  m57: '2026-06-22T17:00:00Z',  // Argentina     vs Austria            (MD2)
  m58: '2026-06-23T03:00:00Z',  // Jordan        vs Algeria            (MD2)
  m59: '2026-06-28T02:00:00Z',  // Jordan        vs Argentina          (MD3)
  m60: '2026-06-28T02:00:00Z',  // Algeria       vs Austria            (MD3)

  // ── Group K: Portugal · DR Congo · Uzbekistan · Colombia ─────────────────
  m61: '2026-06-17T17:00:00Z',  // Portugal      vs DR Congo           (MD1)
  m62: '2026-06-18T02:00:00Z',  // Uzbekistan    vs Colombia           (MD1)
  m63: '2026-06-23T17:00:00Z',  // Portugal      vs Uzbekistan         (MD2)
  m64: '2026-06-24T02:00:00Z',  // Colombia      vs DR Congo           (MD2)
  m65: '2026-06-27T23:30:00Z',  // Colombia      vs Portugal           (MD3)
  m66: '2026-06-27T23:30:00Z',  // DR Congo      vs Uzbekistan         (MD3)

  // ── Group L: England · Croatia · Ghana · Panama ───────────────────────────
  m67: '2026-06-17T20:00:00Z',  // England       vs Croatia            (MD1)
  m68: '2026-06-17T23:00:00Z',  // Ghana         vs Panama             (MD1)
  m69: '2026-06-23T20:00:00Z',  // England       vs Ghana              (MD2)
  m70: '2026-06-23T23:00:00Z',  // Panama        vs Croatia            (MD2)
  m71: '2026-06-27T21:00:00Z',  // Panama        vs England            (MD3)
  m72: '2026-06-27T21:00:00Z',  // Croatia       vs Ghana              (MD3)
}
